project_id = "evdmaqrarpphywizrwhf"

[functions.process-payment]
verify_jwt = false

[functions.send-registration-email]
verify_jwt = false

[functions.dcm-webhook]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-ticket-emails]
verify_jwt = false
